/**
 * Pointili CRM — the data.
 *
 * Extracted from the Meta Business Suite inbox on 26 Sep 2026, 1:25 PM, for the
 * campaign POINTILY TEST1 / ADSET1 (ad_id 120252998562030236). Every lead here
 * arrived from that ad; nothing is invented. `said` holds what was actually
 * typed, trimmed — voice notes are marked because their content is not readable.
 *
 * To update: Claude rewrites this file from new inbox exports. What the app
 * itself changes (stage, next action, notes) is kept in the browser on top of
 * this, so a refresh of the data never erases your own edits.
 */
window.CRM = {
  updated: "2026-09-26T13:25:00+01:00",
  campaign: {
    name: "POINTILY TEST1 · ADSET1",
    ad_id: "120252998562030236",
    started: "2026-09-25",
    destination: "Messenger / Instagram DM",
  },

  /** The playbook's states, in order — social/business/replies.md */
  stages: [
    { id: "lead", label: "Lead", hint: "replied to the ad, nothing qualified yet" },
    { id: "qualified", label: "Qualified", hint: "we know the shop and the zone" },
    { id: "interested", label: "Interested", hint: "wants a time, a demo or an example" },
    { id: "demo", label: "Demo booked", hint: "day and hour agreed" },
    { id: "installed", label: "Installed", hint: "paid on the day, account live" },
    { id: "lost", label: "Lost", hint: "said no, or gone quiet for good" },
  ],

  leads: [
    {
      id: "vapostore",
      name: "Vapostore Gafsa",
      channel: "instagram",
      business: "Vape shop",
      zone: "Gafsa",
      phone: null,
      stage: "interested",
      heat: "hot",
      first: "2026-09-25",
      last: "2026-09-25",
      next: "Listen back to his voice notes and write down what he actually asked — this is the deepest conversation in the whole campaign and nothing of it is in writing.",
      due: "today",
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "them", text: "El client lezmou ysobb application ?" },
        { who: "us", text: "Mar7ba bik 5oya. El 3am b 120 dinar w 6 chhour b 80 dinar" },
        { who: "them", text: "Eyh w kifh application hiya wala chnu" },
        { who: "us", text: "W le el client malezmouch ysob aplication just yscani el qr mte3ik w titzedlou el tab3a fi carta mte3ou. Just awel mara y7il compte b numero mte3o. Simple" },
        { who: "them", text: "🎤 voice 0:12 · 0:07" },
        { who: "us", text: "🎤 voice 0:45 · 0:11 · 0:16" },
        { who: "them", text: "🎤 voice 0:31 · 0:06 · 0:54" },
        { who: "us", text: "🎤 voice 0:33" },
      ],
      note: "Eight voice notes traded both ways — by far the most engaged lead. A vape shop in Gafsa, outside the zone the growth plan picks.",
    },
    {
      id: "hedi-feki",
      name: "Hédi Feki",
      channel: "messenger",
      business: "Pâtisserie",
      zone: "Tunis",
      phone: null,
      stage: "interested",
      heat: "hot",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "You promised him an example this evening — «El 3chiya nchallah nib3atlik exemple fih kol chay». Send it today or the promise is the last thing he remembers.",
      due: "today",
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "them", text: "Pâtisserie" },
        { who: "them", text: "El client lezmou ysobb application ?" },
        { who: "them", text: "Ki nhebbou ya3mel abonnement najjem ? Andkom haja dans ce sens ?" },
        { who: "us", text: "El client mte3ik ? Ken tnijem zid fahamni aktar w nijmou nil9awlik 7al" },
        { who: "us", text: "📞 two missed calls, 10:06" },
        { who: "them", text: "Nheb na3mel abonnement Kima salle de sport. Ta3mlou cette option" },
        { who: "us", text: "Ma3neha t7ib taba3 les abonnement mte3 les client mte3ik w ta3tih houwa interface ytaba3 biha zeda — oui nijmou ni5dmouh el solution. 7ata el soum kif 120 dinar el 3am w 8 chhour b 80 dinar" },
        { who: "us", text: "El 3chiya nchallah nib3atlik exemple fih kol chay" },
        { who: "them", text: "Ok merci beaucoup" },
      ],
      note: "He is not asking for a stamp card. He wants gym-style memberships — tracking who is subscribed and for how long. That is a different product. You answered «oui nijmou ni5dmouh el solution», so decide what you are actually promising before the example goes out. Also: you quoted «8 chhour b 80 dinar» — the plan is 6 months.",
    },
    {
      id: "kaled-makhlouf",
      name: "Kaled Makhlouf",
      channel: "messenger",
      business: "Boutique telifounet",
      zone: null,
      phone: null,
      stage: "interested",
      heat: "hot",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "He said «Bien sur» and you offered to open the account — «Ken mrigel n7iloulik compte w nubdew». Get a day and an hour out of him.",
      due: "today",
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "them", text: "Boutique telifounet" },
        { who: "us", text: "Wada7, ken t7ib 5alili nmrouk w 9oli wa9tech yse3dik, nkalmik w nzid nfahmik kol chay" },
        { who: "us", text: "Inti fehim el system de fidelite ?" },
        { who: "them", text: "Bien sur" },
        { who: "us", text: "Ken mrigel n7iloulik compte w nubdew" },
      ],
      note: "Understood the idea without a demo. Closest thing to a yes in the inbox.",
    },
    {
      id: "brahem-karim",
      name: "Brahem Karim",
      channel: "messenger",
      business: "Boutique de vêtements",
      zone: null,
      phone: "28131507",
      stage: "interested",
      heat: "hot",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "He gave his number unprompted. Call 28 131 507 — a number handed over is the strongest signal in this whole list.",
      due: "today",
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "them", text: "El client lezmou ysobb application ?" },
        { who: "us", text: "Bnj karim. Binisba lil prix 120 dinar el 3am w 80 dinar lil 6 chhour. W el client malezmouch ysob application, just yscani el qr w titzedlou tempen" },
        { who: "us", text: "Andek ay sou2al ken t7ib 5ali nmrouk w nzid nfahmik kol chay" },
        { who: "them", text: "Bonjour fekra behia" },
        { who: "them", text: "Boutique de vêtements" },
        { who: "them", text: "28131507" },
      ],
      note: "«fekra behia» then his phone number. Nothing else needed to be said.",
    },
    {
      id: "sarra-ben-saad",
      name: "Sarra Ben Saad",
      channel: "messenger",
      business: "Café",
      zone: null,
      phone: null,
      stage: "interested",
      heat: "hot",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "She answered «L'après midi» when you asked when to call. That is this afternoon — today.",
      due: "today",
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "us", text: "Bnj sarra, el aswem 120 DT fel 3am wala 80 DT l 6 chhour" },
        { who: "them", text: "Café" },
        { who: "us", text: "Wada7, inti fehma el system w el fikra ? Just ken t7ib 5alili nmrouk w 9oli wa9tech yse3dik bech nkalmik" },
        { who: "them", text: "L'après midi" },
      ],
      note: "A café — the exact shop the product was built for.",
    },
    {
      id: "elamir-elothmani",
      name: "ElAmir ElOthmani",
      channel: "instagram",
      business: null,
      zone: null,
      phone: null,
      stage: "lead",
      heat: "warm",
      first: "2026-09-25",
      last: "2026-09-25",
      next: "Asked what his shop is called on Friday and he never answered. One short nudge, then leave it.",
      due: null,
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "us", text: "120 DT fel 3am wala 80 DT l 6 chhour. El clients mte3ek lkol yesta3mlouha, w kol chay dakhel fel prix. Tkhalles b virement, D17 wala cash." },
        { who: "us", text: "Esm el local mte3ek chnowa?" },
      ],
      note: "Marked Priority in the inbox. Got the full, correct price answer — and still went quiet.",
    },
    {
      id: "abou-yassine",
      name: "ابو ياسين العياري",
      channel: "messenger",
      business: null,
      zone: "Tunis",
      phone: null,
      stage: "lead",
      heat: "warm",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "He replied «?» to the qualifying question — he did not understand it. Ask again in plain words: what kind of shop.",
      due: "today",
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "us", text: "120 DT fel 3am wala 80 DT l 6 chhour. chnou el prject mte3ik bidabt ?" },
        { who: "them", text: "?" },
      ],
      note: "The «?» is the clearest evidence that «chnou el prject mte3ik bidabt» is not landing.",
    },
    {
      id: "couloud-hk",
      name: "Couloud HK",
      channel: "instagram",
      business: null,
      zone: null,
      phone: null,
      stage: "lead",
      heat: "cold",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "Asked both canned questions, got both answers, said nothing since. One nudge.",
      due: null,
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "them", text: "El client lezmou ysobb application ?" },
        { who: "us", text: "Le, ma lezmouch ysobb 7atta application. Yscan-i el QR b camera mta3 téléphone, yda5el numro mta3ou w yabda direct. El tampon yodhher fi la7ditha" },
        { who: "us", text: "Just chnou el prject mte3ik bidabt ?" },
      ],
      note: "Marked Priority.",
    },
    {
      id: "hassan-kamel",
      name: "Hassan Kamel",
      channel: "messenger",
      business: null,
      zone: null,
      phone: null,
      stage: "lead",
      heat: "cold",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "Only ever asked the app question. Nudge once with something concrete, not another question.",
      due: null,
      said: [
        { who: "them", text: "El client lezmou ysobb application ?" },
        { who: "us", text: "Le, ma lezmouch ysobb 7atta application. Yscan-i el QR b camera mta3 téléphone, yda5el numro mta3ou w yabda direct. El tampon yodhher fi la7ditha" },
        { who: "us", text: "chnou el prject mte3ik bidabt ?" },
      ],
      note: null,
    },
    {
      id: "aziz-chaabouni",
      name: "Aziz Chaabouni",
      channel: "instagram",
      business: null,
      zone: null,
      phone: null,
      stage: "lead",
      heat: "cold",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "Price asked and answered ten minutes ago. Still warm enough for one message.",
      due: null,
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "us", text: "120 DT fel 3am wala 80 DT l 6 chhour. chnou el prject mte3ik bidabt ?" },
      ],
      note: null,
    },
    {
      id: "amir-rouis",
      name: "Amir Rouis",
      channel: "instagram",
      business: null,
      zone: null,
      phone: null,
      stage: "lead",
      heat: "cold",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "Same canned exchange, no reply.",
      due: null,
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "us", text: "120 DT fel 3am wala 80 DT l 6 chhour. chnou el prject mte3ik bidabt ?" },
      ],
      note: "Marked Priority.",
    },
    {
      id: "rasta-benzema",
      name: "Rasta Benzema",
      channel: "messenger",
      business: null,
      zone: null,
      phone: null,
      stage: "lead",
      heat: "cold",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "Said «Bnj» and nothing after the price. Nudge.",
      due: null,
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "them", text: "Bnj" },
        { who: "us", text: "120 DT fel 3am wala 80 DT l 6 chhour. chnou el prject mte3ik bidabt ?" },
      ],
      note: null,
    },
    {
      id: "bouzaien-issam",
      name: "Bouzaien Issam",
      channel: "messenger",
      business: null,
      zone: null,
      phone: null,
      stage: "lead",
      heat: "cold",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "Same canned exchange, no reply.",
      due: null,
      said: [
        { who: "them", text: "9addech tkellef Pointili ?" },
        { who: "us", text: "120 DT fel 3am wala 80 DT l 6 chhour. chnou el prject mte3ik bidabt ?" },
      ],
      note: null,
    },
    {
      id: "abir-roukhami",
      name: "abir Roukhami عبير الرخامي",
      channel: "instagram",
      business: null,
      zone: null,
      phone: null,
      stage: "lead",
      heat: "cold",
      first: "2026-09-26",
      last: "2026-09-26",
      next: "Liked a message and never wrote. Not a conversation yet.",
      due: null,
      said: [{ who: "them", text: "♥ liked a message" }],
      note: "Marked Priority by Meta, which on this evidence means nothing.",
    },
    {
      id: "houssem-eljebri",
      name: "HôüSsēm Eėdĩn EljëBrĩ",
      channel: "instagram",
      business: null,
      zone: null,
      phone: null,
      stage: "lead",
      heat: "cold",
      first: "2026-09-25",
      last: "2026-09-25",
      next: "Liked a message on Friday, nothing since.",
      due: null,
      said: [{ who: "them", text: "♥ liked a message" }],
      note: "Marked Priority.",
    },
  ],
};
