/**
 * Every word Abonili says, in its own module.
 *
 * Deliberately NOT in lib/i18n/messages: that registry is bundled into every
 * client page of Pointili, and Abonili's words have no business in Pointili's
 * JavaScript (nor Pointili's in Abonili's). The language itself is shared — the
 * same cookie decides it — but the dictionary is not.
 *
 * French defines the shape; the Tunisian tree must match it key for key.
 */
import { ns, p } from "@/lib/i18n/dict";

export const AB = ns({
  fr: {
    brand: "Abonili",
    tagline: "Les abonnements de votre salle, sans papier.",

    nav: { door: "Entrée", members: "Membres", plans: "Formules", money: "Caisse", settings: "Réglages" },

    status: {
      active: "Valide",
      soon: "Bientôt fini",
      upcoming: "Pas encore commencé",
      expired: "Terminé",
      none: "Sans abonnement",
    },
    kinds: { gym: "Salle de sport", salon: "Salon", terrain: "Terrain", academy: "Académie", pool: "Piscine", other: "Autre" },
    methods: { cash: "Espèces", d17: "D17", transfer: "Virement", card: "Carte", other: "Autre" },

    units: {
      days: p({ one: "{n} jour", other: "{n} jours" }),
      daysLeft: p({ one: "{n} jour restant", other: "{n} jours restants" }),
      sessions: p({ one: "{n} séance", other: "{n} séances" }),
      sessionsLeft: p({ one: "{n} séance restante", other: "{n} séances restantes" }),
      members: p({ one: "{n} membre", other: "{n} membres" }),
      daysBig: p({ one: "jour", other: "jours" }),
      sessionsBig: p({ one: "séance", other: "séances" }),
    },

    login: {
      title: "Connexion",
      hint: "Le compte de votre salle est créé par Pointili, au moment de l'installation.",
      phone: "Téléphone",
      password: "Mot de passe",
      submit: "Entrer",
      wrong: "Numéro ou mot de passe incorrect.",
      invalidPhone: "Numéro tunisien à 8 chiffres.",
      noClub: "Ce compte n'a pas de salle Abonili.",
      noClubHint: "Si vous êtes un commerce Pointili, votre espace est ailleurs.",
      toPointili: "Aller à Pointili",
      help: "Pas de compte ? Écrivez-nous sur WhatsApp.",
      rateLimited: "Trop d'essais. Réessayez dans quelques minutes.",
    },

    door: {
      title: "Entrée",
      placeholder: "N°, nom ou tél.",
      scan: "Scanner la carte",
      scanStop: "Fermer",
      scanHint: "Visez le QR de la carte du membre.",
      cameraDenied: "La caméra est bloquée. Autorisez-la, ou tapez le numéro.",
      nothing: "Personne avec « {q} ».",
      pick: "Plusieurs résultats",
      letIn: "Faire entrer",
      letInAgain: "Faire entrer encore",
      in: "Entré",
      alreadyIn: "Déjà entré aujourd'hui à {time}.",
      renew: "Renouveler",
      open: "Fiche",
      until: "jusqu'au {date}",
      endedOn: "terminé le {date}",
      startsOn: "commence le {date}",
      lastDay: "Dernier jour",
      today: "Aujourd'hui",
      todayEmpty: "Personne n'est encore entré aujourd'hui.",
      statIn: "valides",
      statWeek: "finissent cette semaine",
      statToday: "entrées aujourd'hui",
      next: "Suivant",
      suspended: "Votre salle est suspendue. Contactez Pointili.",
    },

    members: {
      title: "Membres",
      add: "Nouveau membre",
      search: "Chercher un nom, un n° ou un téléphone",
      filters: { all: "Tous", active: "Valides", soon: "Bientôt fini", expired: "Terminés" },
      empty: "Aucun membre ici.",
      emptyAll: "Ajoutez votre premier membre : son abonnement commence tout de suite.",
      noPlans: "Créez d'abord une formule.",
      createPlan: "Créer une formule",
    },

    add: {
      title: "Nouveau membre",
      name: "Nom et prénom",
      namePh: "Salah Ben Ali",
      phone: "Téléphone",
      phoneHint: "Pour lui envoyer sa carte sur WhatsApp. Facultatif.",
      plan: "Formule",
      noPlan: "Pas encore d'abonnement",
      amount: "Payé (DT)",
      method: "Paiement",
      starts: "Début",
      startsToday: "Aujourd'hui",
      note: "Note",
      notePh: "Blessure au genou, horaires…",
      submit: "Ajouter",
      saving: "Ajout…",
      exists: "Ce numéro est déjà membre.",
      openExisting: "Ouvrir sa fiche",
    },

    member: {
      back: "Membres",
      card: "Sa carte",
      cardHint: "Un lien privé : il le garde sur son téléphone et le montre à l'entrée.",
      copy: "Copier le lien",
      copied: "Lien copié",
      whatsapp: "Envoyer sur WhatsApp",
      whatsappText: "Bonjour {name}, voici votre carte {club} : {url}",
      openCard: "Voir la carte",
      renew: "Renouveler",
      addDays: "Ajouter des jours",
      edit: "Modifier",
      history: "Historique",
      visits: "Entrées",
      noVisits: "Aucune entrée pour l'instant.",
      paid: "Payé en tout",
      visitsTotal: "Entrées en tout",
      memberSince: "Membre depuis le {date}",
      period: {
        current: "En cours",
        upcoming: "À venir",
        done: "Terminé",
        cancelled: "Annulé",
      },
      cancelSale: "Annuler cette vente",
      cancelConfirm: "Annuler cette vente ? L'abonnement s'arrête et l'argent sort de la caisse.",
      renewTitle: "Renouveler",
      renewHint: "Le nouvel abonnement commence après celui en cours.",
      renewSubmit: "Encaisser et renouveler",
      daysTitle: "Ajouter des jours",
      daysHint: "Un cadeau, une compensation : repousse la date de fin.",
      daysSubmit: "Ajouter",
      editTitle: "Modifier",
      save: "Enregistrer",
      cancel: "Fermer",
      used: "{used}/{total} séances",
    },

    plans: {
      title: "Formules",
      hint: "Ce que vous vendez. Une formule finit après des jours, des séances, ou les deux.",
      add: "Nouvelle formule",
      name: "Nom",
      namePh: "Mensuel",
      price: "Prix (DT)",
      days: "Durée (jours)",
      sessions: "Séances",
      daysPh: "30",
      sessionsPh: "Illimité",
      limitHint: "Laissez un champ vide pour « sans limite ». Pas les deux.",
      active: "En vente",
      inactive: "Retirée",
      save: "Enregistrer",
      create: "Créer",
      edit: "Modifier",
      cancel: "Fermer",
      onIt: p({ zero: "personne dessus", one: "{n} membre dessus", other: "{n} membres dessus" }),
      empty: "Pas encore de formule.",
      presets: "Idées",
      preset: { month: "Mensuel", quarter: "Trimestriel", year: "Annuel", ten: "10 séances" },
    },

    money: {
      title: "Caisse",
      month: "Ce mois",
      total: "Encaissé",
      previous: "Mois précédent : {amount}",
      sales: p({ zero: "aucune vente", one: "{n} vente", other: "{n} ventes" }),
      byMethod: "Par paiement",
      payments: "Ventes",
      noPayments: "Aucune vente ce mois-ci.",
      due: "À renouveler cette semaine",
      dueHint: "Leur abonnement finit dans les 7 jours et rien ne suit.",
      dueEmpty: "Personne ne finit cette semaine.",
      expected: "Attendu : {amount}",
      remind: "Rappeler",
      remindText: "Bonjour {name}, votre abonnement {club} finit le {date}. On le renouvelle ?",
      prev: "Mois précédent",
      nextMonth: "Mois suivant",
    },

    settings: {
      title: "Réglages",
      club: "Votre salle",
      name: "Nom",
      kind: "Type",
      phone: "Téléphone",
      address: "Adresse",
      save: "Enregistrer",
      saved: "Enregistré",
      password: "Mot de passe",
      current: "Mot de passe actuel",
      newPassword: "Nouveau mot de passe",
      changePassword: "Changer",
      passwordChanged: "Mot de passe changé",
      language: "Langue",
      account: "Compte",
      paidUntil: "Abonnement Abonili payé jusqu'au {date}",
      paidPast: "Votre abonnement Abonili a expiré le {date}. Contactez Pointili.",
      logout: "Se déconnecter",
      support: "Aide sur WhatsApp",
    },

    card: {
      title: "Carte membre",
      show: "Montrez ce QR à l'entrée",
      number: "N°",
      lastVisits: "Dernières entrées",
      none: "Pas encore d'entrée.",
      notFound: "Cette carte n'existe pas.",
      notFoundHint: "Le lien est peut-être incomplet. Demandez à votre salle de vous le renvoyer.",
      poweredBy: "Carte Abonili",
    },

    admin: {
      title: "Abonili",
      subtitle: "Les salles qui tournent sur Abonili",
      newClub: "Ouvrir une salle",
      clubName: "Nom de la salle",
      kind: "Type",
      ownerName: "Nom du gérant",
      ownerPhone: "Téléphone du gérant",
      ownerPhoneHint: "Il se connecte avec ce numéro sur /abonili/login.",
      create: "Créer la salle",
      creating: "Création…",
      created: "Salle créée",
      attached: "Ce numéro avait déjà un compte : la salle y est rattachée, même mot de passe.",
      passwordOnce: "Mot de passe — affiché une seule fois",
      copy: "Copier",
      copied: "Copié",
      another: "Une autre",
      loginAt: "Connexion : {url}",
      none: "Pas encore de salle.",
      stats: "{members} membres · {active} valides · {visits} entrées en 7 j",
      paidUntil: "Payé jusqu'au {date}",
      unpaid: "Paiement non renseigné",
      plusMonth: "+1 mois",
      plusYear: "+1 an",
      suspend: "Suspendre",
      activate: "Réactiver",
      suspended: "Suspendue",
      saved: "Enregistré",
    },

    errors: {
      invalid_name: "Le nom doit faire entre 2 et 80 caractères.",
      invalid_phone: "Numéro tunisien à 8 chiffres.",
      invalid_price: "Prix invalide.",
      invalid_amount: "Montant invalide.",
      invalid_days: "Nombre de jours invalide.",
      invalid_sessions: "Nombre de séances invalide.",
      invalid_date: "Date invalide.",
      invalid_kind: "Type invalide.",
      invalid_method: "Paiement invalide.",
      plan_unlimited: "Une formule doit finir : des jours, des séances, ou les deux.",
      plan_not_found: "Formule introuvable.",
      plan_inactive: "Cette formule n'est plus en vente.",
      too_many_plans: "30 formules au maximum.",
      already_has_club: "Ce compte a déjà une salle.",
      phone_taken: "Ce numéro est déjà membre.",
      not_found: "Introuvable.",
      not_valid: "Pas d'abonnement valide aujourd'hui.",
      already_in: "Déjà entré aujourd'hui.",
      nothing_to_extend: "Aucun abonnement en cours à prolonger.",
      club_suspended: "Votre salle est suspendue. Contactez Pointili.",
      rate_limited: "Trop d'essais. Réessayez dans un moment.",
      network: "Connexion perdue. Réessayez.",
    },
  },

  tn: {
    brand: "Abonili",
    tagline: "الأبونمونات متاع صالتك، بلا ورق.",

    nav: { door: "الباب", members: "المشتركين", plans: "الفورمولات", money: "الكاسة", settings: "الإعدادات" },

    status: {
      active: "صالح",
      soon: "قريب يوفى",
      upcoming: "مازال ما بداش",
      expired: "وفى",
      none: "بلا أبونمون",
    },
    kinds: { gym: "صالة رياضة", salon: "صالون", terrain: "تيران", academy: "أكاديمية", pool: "بيسين", other: "أخرى" },
    methods: { cash: "كاش", d17: "D17", transfer: "فيرمون", card: "كارت", other: "أخرى" },

    units: {
      days: p({ one: "نهار", two: "يومين", few: "{n} أيام", other: "{n} يوم" }),
      daysLeft: p({ one: "يبقالو نهار", two: "يبقالو يومين", few: "يبقالو {n} أيام", other: "يبقالو {n} يوم" }),
      sessions: p({ one: "سيونس", two: "زوز سيونسات", few: "{n} سيونسات", other: "{n} سيونس" }),
      sessionsLeft: p({ one: "تبقالو سيونس", two: "يبقالو زوز سيونسات", few: "يبقالو {n} سيونسات", other: "يبقالو {n} سيونس" }),
      members: p({ one: "مشترك", two: "زوز مشتركين", few: "{n} مشتركين", other: "{n} مشترك" }),
      daysBig: p({ one: "نهار", two: "يوم", few: "أيام", other: "يوم" }),
      sessionsBig: p({ one: "سيونس", two: "سيونس", few: "سيونسات", other: "سيونس" }),
    },

    login: {
      title: "الدخول",
      hint: "الكونت متاع صالتك يتحلّ من عند Pointili، نهار التركيب.",
      phone: "التليفون",
      password: "كلمة السر",
      submit: "أدخل",
      wrong: "النومرو ولا كلمة السر غالطين.",
      invalidPhone: "نومرو تونسي بـ 8 أرقام.",
      noClub: "الكونت هذا ما عندوش صالة في Abonili.",
      noClubHint: "كان عندك محل في Pointili، بلاصتك موش هوني.",
      toPointili: "روح لـ Pointili",
      help: "ما عندكش كونت؟ ابعثلنا في واتساب.",
      rateLimited: "برشا محاولات. عاود بعد شوية.",
    },

    door: {
      title: "الباب",
      placeholder: "نومرو، إسم ولا تليفون",
      scan: "سكاني الكارت",
      scanStop: "سكّر",
      scanHint: "وجّه الكاميرا للـ QR اللي في كارت المشترك.",
      cameraDenied: "الكاميرا مسكّرة. حلّها، ولا اكتب النومرو.",
      nothing: "حتى حد بـ «{q}».",
      pick: "فمّا أكثر من واحد",
      letIn: "دخّل",
      letInAgain: "دخّلو مرّة أخرى",
      in: "دخل",
      alreadyIn: "دخل اليوم مع {time}.",
      renew: "جدّد",
      open: "الفيشة",
      until: "حتى {date}",
      endedOn: "وفى نهار {date}",
      startsOn: "يبدا نهار {date}",
      lastDay: "آخر نهار",
      today: "اليوم",
      todayEmpty: "حتى حد ما دخل اليوم.",
      statIn: "صالحين",
      statWeek: "يوفاو هالجمعة",
      statToday: "دخلو اليوم",
      next: "اللي بعدو",
      suspended: "الصالة متاعك موقوفة. كلّم Pointili.",
    },

    members: {
      title: "المشتركين",
      add: "مشترك جديد",
      search: "لوّج بالإسم، النومرو ولا التليفون",
      filters: { all: "الكل", active: "صالحين", soon: "قريب يوفاو", expired: "وفاو" },
      empty: "حتى حد هوني.",
      emptyAll: "زيد أول مشترك: الأبونمون متاعو يبدا توّا.",
      noPlans: "اعمل فورمول قبل.",
      createPlan: "اعمل فورمول",
    },

    add: {
      title: "مشترك جديد",
      name: "الإسم واللقب",
      namePh: "صالح بن علي",
      phone: "التليفون",
      phoneHint: "باش تبعثلو الكارت متاعو في واتساب. موش لازم.",
      plan: "الفورمول",
      noPlan: "مازال بلا أبونمون",
      amount: "خلّص (د.ت)",
      method: "الخلاص",
      starts: "يبدا",
      startsToday: "اليوم",
      note: "ملاحظة",
      notePh: "ضربة في الركبة، الأوقات…",
      submit: "زيد",
      saving: "قاعد يزيد…",
      exists: "النومرو هذا مشترك من قبل.",
      openExisting: "حلّ الفيشة متاعو",
    },

    member: {
      back: "المشتركين",
      card: "الكارت متاعو",
      cardHint: "لينك خاص بيه: يخلّيه في التليفون ويورّيه في الباب.",
      copy: "انسخ اللينك",
      copied: "اللينك تنسخ",
      whatsapp: "ابعثها في واتساب",
      whatsappText: "عسلامة {name}، هاذي الكارت متاعك في {club}: {url}",
      openCard: "شوف الكارت",
      renew: "جدّد",
      addDays: "زيد أيام",
      edit: "بدّل",
      history: "التاريخ",
      visits: "الدخلات",
      noVisits: "مازال ما دخل حتى مرّة.",
      paid: "خلّص في الكل",
      visitsTotal: "الدخلات في الكل",
      memberSince: "مشترك من {date}",
      period: {
        current: "ماشي",
        upcoming: "جاي",
        done: "وفى",
        cancelled: "ملغي",
      },
      cancelSale: "ألغي البيعة هاذي",
      cancelConfirm: "تلغي البيعة هاذي؟ الأبونمون يوقف والفلوس تخرج من الكاسة.",
      renewTitle: "جدّد",
      renewHint: "الأبونمون الجديد يبدا كي يوفى اللي ماشي.",
      renewSubmit: "خلّص وجدّد",
      daysTitle: "زيد أيام",
      daysHint: "هدية ولا تعويض: يأخّر نهار النهاية.",
      daysSubmit: "زيد",
      editTitle: "بدّل",
      save: "سجّل",
      cancel: "سكّر",
      used: "{used}/{total} سيونس",
    },

    plans: {
      title: "الفورمولات",
      hint: "شنوّة تبيع. الفورمول يوفى بالأيام، بالسيونسات، ولا بالزوز.",
      add: "فورمول جديد",
      name: "الإسم",
      namePh: "شهري",
      price: "السوم (د.ت)",
      days: "المدة (أيام)",
      sessions: "السيونسات",
      daysPh: "30",
      sessionsPh: "بلا حد",
      limitHint: "خلّي خانة فارغة كان تحب «بلا حد». موش الزوز.",
      active: "للبيع",
      inactive: "مسكّر",
      save: "سجّل",
      create: "اعمل",
      edit: "بدّل",
      cancel: "سكّر",
      onIt: p({ zero: "حتى حد عليه", one: "مشترك عليه", two: "زوز عليه", few: "{n} عليه", other: "{n} عليه" }),
      empty: "مازال ما عملت حتى فورمول.",
      presets: "أفكار",
      preset: { month: "شهري", quarter: "3 شهور", year: "عام", ten: "10 سيونسات" },
    },

    money: {
      title: "الكاسة",
      month: "هالشهر",
      total: "دخل",
      previous: "الشهر اللي فات: {amount}",
      sales: p({ zero: "حتى بيعة", one: "بيعة", two: "زوز بيعات", few: "{n} بيعات", other: "{n} بيعة" }),
      byMethod: "كيفاش خلّصو",
      payments: "البيعات",
      noPayments: "حتى بيعة هالشهر.",
      due: "لازم يجدّدو هالجمعة",
      dueHint: "الأبونمون متاعهم يوفى في 7 أيام وما فمّا شي بعدو.",
      dueEmpty: "حتى حد ما يوفى هالجمعة.",
      expected: "المستنّي: {amount}",
      remind: "فكّرو",
      remindText: "عسلامة {name}، الأبونمون متاعك في {club} يوفى نهار {date}. نجدّدوه؟",
      prev: "الشهر اللي فات",
      nextMonth: "الشهر الجاي",
    },

    settings: {
      title: "الإعدادات",
      club: "الصالة متاعك",
      name: "الإسم",
      kind: "النوع",
      phone: "التليفون",
      address: "العنوان",
      save: "سجّل",
      saved: "تسجّل",
      password: "كلمة السر",
      current: "كلمة السر الحالية",
      newPassword: "كلمة السر الجديدة",
      changePassword: "بدّل",
      passwordChanged: "كلمة السر تبدّلت",
      language: "اللغة",
      account: "الكونت",
      paidUntil: "الأبونمون متاع Abonili خالص حتى {date}",
      paidPast: "الأبونمون متاع Abonili وفى نهار {date}. كلّم Pointili.",
      logout: "أخرج",
      support: "عاونّي في واتساب",
    },

    card: {
      title: "كارت المشترك",
      show: "ورّي الـ QR هذا في الباب",
      number: "نومرو",
      lastVisits: "آخر الدخلات",
      none: "مازال ما دخلت حتى مرّة.",
      notFound: "الكارت هاذي موش موجودة.",
      notFoundHint: "يمكن اللينك ناقص. اطلب من الصالة تعاود تبعثهولك.",
      poweredBy: "كارت Abonili",
    },

    admin: {
      title: "Abonili",
      subtitle: "الصالات اللي تخدم بـ Abonili",
      newClub: "حلّ صالة",
      clubName: "إسم الصالة",
      kind: "النوع",
      ownerName: "إسم مولى الصالة",
      ownerPhone: "تليفون مولى الصالة",
      ownerPhoneHint: "بالنومرو هذا يدخل في /abonili/login.",
      create: "اعمل الصالة",
      creating: "قاعد يتعمل…",
      created: "الصالة تعملت",
      attached: "النومرو هذا عندو كونت من قبل: الصالة تزادت عليه، نفس كلمة السر.",
      passwordOnce: "كلمة السر — تتورّى مرة وحدة برك",
      copy: "انسخ",
      copied: "تنسخ",
      another: "وحدة أخرى",
      loginAt: "الدخول: {url}",
      none: "مازال حتى صالة.",
      stats: "{members} مشترك · {active} صالحين · {visits} دخلة في 7 أيام",
      paidUntil: "خالص حتى {date}",
      unpaid: "الخلاص مازال ما تسجّلش",
      plusMonth: "+1 شهر",
      plusYear: "+1 عام",
      suspend: "وقّف",
      activate: "رجّع",
      suspended: "موقوفة",
      saved: "تسجّل",
    },

    errors: {
      invalid_name: "الإسم لازم بين 2 و 80 حرف.",
      invalid_phone: "نومرو تونسي بـ 8 أرقام.",
      invalid_price: "السوم موش صحيح.",
      invalid_amount: "المبلغ موش صحيح.",
      invalid_days: "عدد الأيام موش صحيح.",
      invalid_sessions: "عدد السيونسات موش صحيح.",
      invalid_date: "التاريخ موش صحيح.",
      invalid_kind: "النوع موش صحيح.",
      invalid_method: "طريقة الخلاص موش صحيحة.",
      plan_unlimited: "الفورمول لازم يوفى: بالأيام، بالسيونسات، ولا بالزوز.",
      plan_not_found: "الفورمول موش موجود.",
      plan_inactive: "الفورمول هذا ما عادش للبيع.",
      too_many_plans: "30 فورمول على الأكثر.",
      already_has_club: "الكونت هذا عندو صالة من قبل.",
      phone_taken: "النومرو هذا مشترك من قبل.",
      not_found: "موش موجود.",
      not_valid: "ما عندوش أبونمون صالح اليوم.",
      already_in: "دخل اليوم من قبل.",
      nothing_to_extend: "ما فمّا حتى أبونمون ماشي باش نطوّلو.",
      club_suspended: "الصالة متاعك موقوفة. كلّم Pointili.",
      rate_limited: "برشا محاولات. عاود بعد شوية.",
      network: "الكونكسيون طاحت. عاود.",
    },
  },
});

export type AbCopy = (typeof AB)["fr"];
