/**
 * Every word of Pointili v2, in Tunisian. One file, so the whole app can be
 * read (and checked) in one sitting. {name} placeholders are filled by fill().
 */
export const t = {
  brand: "Pointili",
  tagline: "كارطات الفيدليتي متاعك، في تليفونك",
  createAccount: "اعمل كونت",
  haveAccount: "عندي كونت",
  shopLink: "عندك محل؟",
  shopLinkCta: "ابدا من هوني",
  iAmCustomer: "نلمّ التامبونات",
  iAmCustomerHint: "كارطات المحلات اللي تحبّهم، في تليفونك",
  iAmShop: "نعطي التامبونات",
  iAmShopHint: "حلّ كارط فيديليتي لمحلّك في دقيقتين",
  haveAccountLogin: "عندك كونت؟ ادخل",
  back: "ارجع",
  next: "كمّل",
  ok: "باهي",
  logout: "اخرج",

  // auth
  joinTitle: "اعمل كونت",
  joinHint: "بنومرو التليفون وخلاص",
  loginTitle: "مرحبا بيك",
  loginHint: "ادخل بنومرو التليفون",
  name: "إسمك",
  namePh: "مثلا: سامي",
  phone: "نومرو التليفون",
  password: "كلمة السر",
  passwordPh: "8 حروف ولا أرقام على الأقل",
  join: "اعمل الكونت",
  login: "ادخل",
  toLogin: "عندك كونت؟ ادخل",
  toJoin: "ما عندكش كونت؟ اعمل واحد",
  errPhone: "النومرو لازمو 8 أرقام",
  errPassword: "كلمة السر لازمها 8 حروف ولا أرقام على الأقل",
  errName: "اكتب إسمك",
  errLogin: "النومرو ولا كلمة السر غالطين",
  errTaken: "النومرو هذا عندو كونت. ادخل بيه",
  errNetwork: "صار مشكل. عاود جرّب",
  errTooMany: "برشا محاولات. استنّى ربع ساعة وعاود",
  forgot: "نسيت كلمة السر؟",
  forgotBody: "ابعثلنا ميساج على الواتساب من نفس النومرو، ونبعثولك كلمة سر جديدة.",
  forgotCta: "ابعثلنا على الواتساب",
  forgotMsg: "سلام، نسيت كلمة السر متاعي في Pointili",
  forgotNoContact: "قول للمحل اللي تتعامل معاه، وهو يكلّمنا.",
  newPassword: "كلمة سر جديدة",
  passwordChanged: "تبدّلت كلمة السر",
  change: "بدّل",
  openShop: "عندك محل؟",
  openShopHint: "حلّ كارط فيديليتي لمحلّك",
  myCardsHint: "الكارطات اللي لمّيتها في المحلات",

  // the scan
  checking: "لحظة…",
  newStamp: "تامبون جديد!",
  reserved: "حجزنالك التامبون",
  reservedBody: "اعمل كونت باش يولّي متاعك",
  reservedClock: "عندك 20 دقيقة",
  toGo: "مازالولك {n} باش تربح {gift}",
  toGoOne: "مازالك تامبون واحد باش تربح {gift}",
  won: "ربحت {gift}!",
  wonBody: "ورّي الشاشة هذي للمحل",
  seeCard: "شوف الكارط",
  done: "باهي",
  errUsed: "الكود هذا تاخذ",
  errUsedBody: "سكاني الكود اللي على الشاشة توّا",
  errExpired: "الكود وفى",
  errExpiredBody: "سكاني الكود اللي على الشاشة توّا",
  errSoon: "خذيت تامبون هوني قبل شوية",
  errSoonBody: "نتلاقاو المرّة الجاية! التامبون الجاي من {time}",
  errDone: "التامبون هذا خذيتو",
  errOwn: "هذا المحل متاعك 🙂",
  errOwnBody: "الكود هذا للحرفاء",
  errInvalid: "الكود هذا موش صحيح",
  errPaused: "المحل هذا موقّف التامبونات توّا",
  scanAgain: "سكاني من جديد",

  // the wallet
  hello: "نهارك طيّب",
  myCards: "الكارطات متاعي",
  noCards: "ما عندكش كارطات مازال",
  noCardsBody: "سكاني الكود في المحل وخوذ أول تامبون",
  scan: "سكاني",
  giftWaiting: "عندك كادو يستنّى فيك",
  giftAt: "{gift} في {shop}",
  stamps: "{n} تامبونات",

  // a card
  ready: "الكادو متاعك حاضر!",
  readyBody: "ورّي الشاشة هذي للمحل",
  history: "شنوّة صار",
  hStamp: "تامبون",
  hGift: "خذيت {gift}",
  hGiftWaiting: "كادو يستنّى",
  nothingYet: "مازال ما صار شي",
  nextCard: "المحل بدّل الكارط: بعد الكادو هذا تولّي {gift} بعد {n}.",

  // the camera
  scanTitle: "سكاني الكود",
  scanHint: "حط الكود متاع المحل في الإطار",
  cameraOff: "الكاميرا ما خدمتش",
  cameraOffBody: "خلّي الكاميرا تخدم، ولا سكاني بكاميرا التليفون",
  photo: "صوّر الكود",

  // the account
  account: "الكونت",
  save: "سجّل",
  saved: "تسجّل",

  // the owner: open the shop
  shopNewTitle: "حلّ محلّك في Pointili",
  shopNewHint: "دقيقتين وتبدا تعطي تامبونات",
  ownerName: "إسمك",
  shopTitle: "المحل",
  shopName: "إسم المحل",
  shopNamePh: "مثلا: Café Yasmine",
  shopKind: "شنوّة يبيع؟",
  kindsAll: "الكل",
  kindsTitle: "شنوّة يبيع محلّك؟",
  kindsSearch: "لوّج: عطورات، فريب، حمّام…",
  kindsNone: "ما لقيناش. اختار «آخر»",
  kinds: {
    cafe: "قهوة",
    juice: "عصير وجلاطي",
    bakery: "مخبزة",
    pastry: "حلويات",
    viennoiserie: "فطاير وكرواسون",
    crepes: "كريب وغوفر",
    restaurant: "ريستو",
    fastfood: "فاست فود",
    snack: "كسكروت وملاوي",
    pizza: "بيتزا",
    grill: "مشوي",
    grocery: "عطّار",
    market: "مغازة",
    butcher: "جزّار",
    fish: "حوت",
    veggies: "خضرة وغلّة",
    roastery: "محمصة",
    barber: "حلّاق",
    hair: "كوافير",
    beauty: "تجميل",
    nails: "أظافر",
    perfume: "عطورات",
    parapharmacy: "بارافارماسي",
    hammam: "حمّام",
    optics: "نظّارات",
    gym: "رياضة",
    clothes: "ملابس",
    fripe: "فريب",
    shoes: "صبابط",
    bags: "ساكوات",
    jewelry: "بيجوتري",
    phones: "تليفونات",
    electronics: "إلكترونيك",
    books: "مكتبة",
    toys: "لعب صغار",
    gifts: "كادوات",
    flowers: "ورد",
    pets: "حيوانات",
    hardware: "دروقري",
    carwash: "لافاج",
    mechanic: "ميكانيك",
    laundry: "بريسينغ",
    tailor: "خيّاط",
    print: "طباعة",
    photo: "تصوير",
    courses: "دروس",
    games: "ألعاب",
    pitch: "ملاعب فوت",
    events: "حفلات",
    other: "آخر",
  } as Record<string, string>,
  cardTitle: "الكارط",
  cardGoal: "قدّاش من تامبون؟",
  cardGift: "شنوّة الكادو؟",
  cardGiftPh: "مثلا: قهوة بلاش",
  cardColor: "اللون",
  cardDone: "حلّ الكود",
  cardNoteNone: "حتى حريف ما بدا الكارط: الجديدة تبدا للكل توّا.",
  cardNoteEase: "اللي بداو الكارط ({who}) يستفادو بالجديدة توّا.",
  cardNoteKeep: "اللي بداو الكارط ({who}) يكمّلوها كيما هي، والجديدة تبدالهم بعد الكادو.",
  ideas: {
    cafe: ["قهوة بلاش", "كابوسان بلاش", "كرواسون بلاش"],
    juice: ["عصير بلاش", "جلاطي بلاش", "ميلك شيك بلاش"],
    bakery: ["خبزة بلاش", "كرواسون بلاش", "قطعة قاتو بلاش"],
    pastry: ["قطعة قاتو بلاش", "كيلو حلويات بريميز", "ميلفاي بلاش"],
    viennoiserie: ["كرواسون بلاش", "فطيرة بلاش", "قهوة وكرواسون"],
    crepes: ["كريب بلاش", "غوفر بلاش", "مشروب بلاش"],
    snack: ["كسكروت بلاش", "ملاوي بلاش", "مشروب بلاش"],
    restaurant: ["ديسار بلاش", "مشروب بلاش", "صحن بلاش"],
    fastfood: ["سندويتش بلاش", "فريت ومشروب بلاش", "مشروب بلاش"],
    pizza: ["بيتزا صغيرة بلاش", "مشروب بلاش", "ديسار بلاش"],
    grill: ["صحن مشوي بلاش", "مشروب بلاش", "سلطة بلاش"],
    market: ["ريميز 5 د", "ريميز 10 د", "كادو مفاجأة"],
    butcher: ["كيلو مرقاز بلاش", "ريميز 5 د", "ريميز 10%"],
    fish: ["كيلو سردينة بلاش", "تنظيف الحوت بلاش", "ريميز 5 د"],
    veggies: ["كيلو غلّة بلاش", "ريميز 3 د", "كادو مفاجأة"],
    roastery: ["ربع كاكاوية بلاش", "ربع قلوب بلاش", "ريميز 10%"],
    barber: ["حجامة بلاش", "تعديل اللحية بلاش", "ريميز 10 د"],
    hair: ["بروشينغ بلاش", "سوان شعر بلاش", "ريميز 20%"],
    beauty: ["سوان وجه بلاش", "ريميز 20%", "كادو مفاجأة"],
    nails: ["مانيكير بلاش", "فارني بلاش", "ريميز 20%"],
    perfume: ["عطر صغير بلاش", "ريميز 20%", "تغليف كادو بلاش"],
    parapharmacy: ["ريميز 10%", "كريمة بلاش", "كادو مفاجأة"],
    hammam: ["دخلة حمّام بلاش", "تكييسة بلاش", "ريميز 20%"],
    optics: ["ريميز 20%", "تعديل النظّارات بلاش", "كادو مفاجأة"],
    clothes: ["ريميز 10%", "ريميز 20 د", "كادو مفاجأة"],
    fripe: ["قطعة بلاش", "ريميز 10%", "كادو مفاجأة"],
    shoes: ["ريميز 10%", "ريميز 20 د", "كادو مفاجأة"],
    bags: ["ريميز 10%", "أكسسوار بلاش", "كادو مفاجأة"],
    jewelry: ["أكسسوار بلاش", "ريميز 20%", "تغليف كادو بلاش"],
    phones: ["كوك بلاش", "شارجور بلاش", "ريميز 10%"],
    electronics: ["كاسك بلاش", "شارجور بلاش", "ريميز 10%"],
    books: ["كرّاس بلاش", "ستيلو بلاش", "ريميز 10%"],
    toys: ["لعبة صغيرة بلاش", "ريميز 10%", "تغليف كادو بلاش"],
    flowers: ["وردة بلاش", "ريميز 10%", "تغليف بلاش"],
    pets: ["ماكلة بلاش", "ريميز 10%", "كادو مفاجأة"],
    hardware: ["ريميز 10%", "ريميز 5 د", "كادو مفاجأة"],
    grocery: ["ريميز 5 د", "كادو مفاجأة", "قهوة بلاش"],
    gym: ["سيانس بلاش", "شهر بريميز", "مشروب بروتين بلاش"],
    games: ["بارتية بلاش", "ساعة بلاش", "كادو مفاجأة"],
    events: ["ريميز 10%", "كادو مفاجأة", "صورة بلاش"],
    carwash: ["لافاج بلاش", "تنظيف داخل بلاش", "ريميز 50%"],
    mechanic: ["فيدونج بلاش", "تشخيص بلاش", "ريميز 20%"],
    laundry: ["قطعة بلاش", "ريميز 20%", "كادو مفاجأة"],
    tailor: ["تقصير بلاش", "تصليح بلاش", "ريميز 20%"],
    print: ["10 صفحات بلاش", "تجليد بلاش", "ريميز 20%"],
    photo: ["صورة بلاش", "تصاور هوية بلاش", "ريميز 20%"],
    courses: ["حصّة بلاش", "ريميز 20%", "شهر بريميز"],
    pitch: ["ماتش بلاش", "ساعة بلاش", "مشروب بلاش"],
    gifts: ["ريميز 10%", "تغليف بلاش", "كادو مفاجأة"],
    other: ["كادو بلاش", "ريميز 10 د", "كادو مفاجأة"],
  } as Record<string, string[]>,
  preview: "هكّا يشوفها الحريف",

  // the counter
  counterTitle: "سكاني وخوذ تامبون",
  counterHint: "الكود يتبدّل وحدو، ويخدم مرّة برك",
  someone: "حريف",
  giftFor: "{who} ربح {gift}",
  giveNow: "اعطيه الكادو، وبعد اضغط",
  given: "عطيتو ✓",
  noCardYet: "اعمل الكارط قبل",
  reconnecting: "نعاود نتصل…",

  // the owner's home
  showCode: "ورّي الكود",
  showCodeHint: "الحريف يسكاني ويخوذ تامبون",
  todayTitle: "اليوم",
  numVisitors: "حريف جا",
  waitingTitle: "كوادو يستنّاو",
  lately: "آخر حركة",
  lateStamp: "{who} خذا تامبون",
  lateGift: "{who} ربح {gift}",
  lateGiven: "{who} خذا {gift}",
  options: "الخيارات",
  customersTitle: "الحرفاء",
  customersEmpty: "مازال حتى حريف",
  customersEmptyBody: "ورّي الكود للحرفاء وكل واحد يسكاني يولّي هوني",
  never: "مازال",
  pausedBanner: "المحل موقّف من Pointili. كلّمنا.",
  ago: "قبل {n}",

  // the owner's settings
  settings: "المحل",
  numCustomers: "حريف",
  numToday: "تامبون اليوم",
  numGifts: "كادو تعطى",
  editCard: "بدّل الكارط",
  editShop: "بدّل المحل",
  openCounter: "حلّ الكود",

  // the founder's console
  admin: "الأدمين",
  aShops: "المحلات",
  aPeople: "الناس",
  aPaused: "موقّف",
  aCustomers: "حرفاء",
  aStamps: "تامبون في الكل",
  aToday: "تامبون اليوم",
  aGiven: "كادو تعطى",
  aWeek: "التامبونات، آخر 7 أيّام",
  aAllLive: "الكل يخدمو",
  aInAll: "في الكل",
  aNoneWaiting: "حتى كادو ما يستنّى",
  aCall: "كلّمو",
  aSearch: "لوّج بالاسم ولا النومرو",
  aNoCard: "ما عملش الكارط",
  aOwner: "المولى",
  aCreated: "تحلّ",
  aLast: "آخر حركة",
  aPause: "وقّف المحل",
  aResume: "رجّع المحل يخدم",
  aDelete: "امسح المحل",
  aDeleteConfirm: "متأكد؟ المحل والكارطات متاعو يتمسحو ما يرجعوش.",
  aTop: "أكثر الحرفاء",
  aRecent: "آخر الحركة",
  aCards: "كارطات",
  aShopOf: "محل",
  aAdminBadge: "أدمين",
  aNothing: "ما فمّا شي",
  aCardsOf: "الكارطات متاعو",
  aNoCardsOf: "ما عندو حتى كارط",
  aIsAdmin: "هذا أدمين: ما يتبدّلش من هوني",
  aReset: "اعطيه كلمة سر جديدة",
  aResetDone: "كلمة السر الجديدة",
  aResetHint: "ما تظهرش مرّة أخرى. ابعثهالو توّا، ويبدّلها من الكونت متاعو.",
  aResetSend: "ابعثها على الواتساب",
  aResetMsg: "سلام {name}، كلمة السر الجديدة متاعك في Pointili: {password}",
  aDeletePerson: "امسح الكونت",
  aDeletePersonConfirm: "متأكد؟ الكونت والكارطات متاعو يتمسحو ما يرجعوش، وكان عندو محل يتمسح زادة.",
};

/** "مازالولك {n}" + { n: 3 } → "مازالولك 3" */
export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => (k in vars ? String(vars[k]) : `{${k}}`));
}

/** The 3D picture of a kind of shop. */
export function kindIcon(kind: string | null | undefined): string {
  return (
    {
      cafe: "coffee",
      juice: "juice",
      bakery: "bread",
      pastry: "cake",
      viennoiserie: "croissant",
      crepes: "waffle",
      restaurant: "plate",
      fastfood: "burger",
      snack: "flatbread",
      pizza: "pizza",
      grill: "poultry",
      grocery: "shop",
      market: "cart",
      butcher: "meat",
      fish: "fish",
      veggies: "carrot",
      roastery: "peanuts",
      barber: "barber",
      hair: "scissors",
      beauty: "lipstick",
      nails: "nailpolish",
      perfume: "lotion",
      parapharmacy: "pill",
      hammam: "soap",
      optics: "glasses",
      gym: "biceps",
      clothes: "dress",
      fripe: "tshirt",
      shoes: "shoe",
      bags: "handbag",
      jewelry: "ring",
      phones: "phone",
      electronics: "headphone",
      books: "books",
      toys: "teddy",
      gifts: "gift",
      flowers: "bouquet",
      pets: "paw",
      hardware: "toolbox",
      carwash: "car",
      mechanic: "wrench",
      laundry: "basket",
      tailor: "thread",
      print: "printer",
      photo: "camera",
      courses: "gradcap",
      games: "videogame",
      pitch: "soccer",
      events: "party",
      // the first app's kinds, should one ever come back
      salon: "scissors",
      shop: "shop",
    } as Record<string, string>
  )[kind ?? ""] ?? "pin";
}

/** Every kind of shop, in the order the owner sees them. */
export const KINDS = Object.keys(t.kinds);

/** The kinds in five groups, for the full list. */
export const KIND_GROUPS: { id: string; label: string; kinds: string[] }[] = [
  { id: "food", label: "ماكلة وشراب", kinds: ["cafe", "juice", "bakery", "pastry", "viennoiserie", "crepes", "restaurant", "fastfood", "snack", "pizza", "grill"] },
  { id: "house", label: "قضية الدار", kinds: ["grocery", "market", "butcher", "fish", "veggies", "roastery"] },
  { id: "beauty", label: "جمال وصحّة", kinds: ["barber", "hair", "beauty", "nails", "perfume", "parapharmacy", "hammam", "optics", "gym"] },
  { id: "things", label: "حوايج", kinds: ["clothes", "fripe", "shoes", "bags", "jewelry", "phones", "electronics", "books", "toys", "gifts", "flowers", "pets", "hardware"] },
  { id: "services", label: "خدمات وترفيه", kinds: ["carwash", "mechanic", "laundry", "tailor", "print", "photo", "courses", "games", "pitch", "events", "other"] },
];

/** The words an owner may type for a kind, besides its name: French, and other ways to say it. */
const KIND_WORDS: Record<string, string> = {
  cafe: "cafe coffee salon de the كافي شاي تاي شيشة قهاوي",
  juice: "jus glace ice cream milkshake عصاير ڤلاس",
  bakery: "boulangerie pain خبز كوشة",
  pastry: "patisserie gateau قاتو باتيسري",
  viennoiserie: "croissant viennoiserie فطايري",
  crepes: "crepe gaufre waffle",
  restaurant: "restaurant resto مطعم",
  fastfood: "fast food burger tacos makloub مقلوب بورغر تاكوس",
  snack: "sandwich casse croute chapati malfouf ملفوف شباتي لبلابي",
  pizza: "pizza pizzeria",
  grill: "grill rotisserie chawarma شوارمة روتيسري دجاج",
  grocery: "epicerie حانوت عطرية",
  market: "supermarche supermarket magasin general سوبرات",
  butcher: "boucherie boucher لحم",
  fish: "poissonnerie poisson حوّات",
  veggies: "fruits legumes خضّار غلال",
  roastery: "fruits secs noix cacahuete قلوب كاكاوية",
  barber: "barbier coiffeur homme حجامة",
  hair: "coiffure coiffeuse salon",
  beauty: "esthetique institut beaute cosmetique مكياج",
  nails: "ongles manucure",
  perfume: "parfum parfumerie عطر",
  parapharmacy: "parapharmacie pharmacie صيدلية",
  hammam: "hammam spa massage مساج",
  optics: "opticien lunettes",
  gym: "salle de sport fitness musculation",
  clothes: "vetements pret a porter boutique حوايج",
  fripe: "friperie",
  shoes: "chaussures sabbat",
  bags: "sacs maroquinerie accessoires",
  jewelry: "bijouterie bijoux مصوغ ذهب",
  phones: "telephone gsm portable",
  electronics: "electronique informatique",
  books: "librairie papeterie كتب",
  toys: "jouets enfants",
  gifts: "cadeaux",
  flowers: "fleuriste fleurs",
  pets: "animalerie animaux",
  hardware: "droguerie quincaillerie",
  carwash: "lavage voiture",
  mechanic: "garage mecanique",
  laundry: "pressing blanchisserie",
  tailor: "couture couturier",
  print: "imprimerie impression photocopie",
  photo: "photographe studio",
  courses: "cours formation ecole",
  games: "jeux playstation billard bowling",
  pitch: "foot football terrain تيران",
  events: "fetes mariage evenement",
  other: "autre",
};

/** Letters that are written several ways become one: أ إ آ → ا, ة → ه, ى → ي, no accents. */
export function plain(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f\u064b-\u065f\u0670]/g, "")
    .replace(/[أإآ]/g, "ا")
    .replace(/ة/g, "ه")
    .replace(/ى/g, "ي")
    .replace(/\s+/g, " ")
    .trim();
}

/** Does this kind answer what the owner typed? Every word has to be found. */
export function kindMatches(kind: string, query: string): boolean {
  const hay = plain(`${t.kinds[kind] ?? ""} ${KIND_WORDS[kind] ?? ""} ${kind}`);
  return plain(query)
    .split(" ")
    .filter(Boolean)
    .every((w) => hay.includes(w));
}

/** Counting the Tunisian way: حريف واحد, زوز حرفاء, 5 حرفاء, 12 حريف. */
export function counted(n: number, one: string, two: string, few: string, many: string): string {
  if (n === 1) return one;
  if (n === 2) return two;
  const r = n % 100;
  return r >= 3 && r <= 10 ? `${n} ${few}` : `${n} ${many}`;
}
export const stampsN = (n: number) => counted(n, "تامبون واحد", "زوز تامبونات", "تامبونات", "تامبون");
export const customersN = (n: number) => counted(n, "حريف واحد", "زوز حرفاء", "حرفاء", "حريف");
/** The same gift, written twice: «قهوة بلاش» = «  قهوة  بلاش » (as the database's same_gift sees it). */
const squash = (x: string | null | undefined) => (x ?? "").trim().replace(/\s+/g, " ").toLowerCase();
export const sameGift = (a: string | null | undefined, b: string | null | undefined) => squash(a) === squash(b);
export const giftsN = (n: number) => counted(n, "كادو واحد", "زوز كادوات", "كادوات", "كادو");
export const accountsN = (n: number) => counted(n, "كونت واحد", "زوز كونتات", "كونتات", "كونت");
export const liveN = (n: number) => counted(n, "واحد يخدم", "زوز يخدمو", "يخدمو", "يخدمو");
export const pausedN = (n: number) => counted(n, "واحد موقّف", "زوز موقّفين", "موقّفين", "موقّفين");
/** كادو واحد يستنّى, زوز كادوات يستنّاو */
export const waitingN = (n: number) => (n === 0 ? t.aNoneWaiting : n === 1 ? `${giftsN(1)} يستنّى` : `${giftsN(n)} يستنّاو`);
