/**
 * Every word of Pointili v2, in Tunisian. One file, so the whole app can be
 * read (and checked) in one sitting. {name} placeholders are filled by fill().
 */
export const t = {
  brand: "Pointili",
  tagline: "كارطات الفيدليتي متاعك، في تليفونك",
  createAccount: "اعمل كونت",
  haveAccount: "عندي كونت",
  enterAsShop: "ادخل كمولى محل",
  enterAsCustomer: "ادخل كحريف",
  haveAccountLogin: "عندك كونت؟ ادخل",
  back: "ارجع",
  next: "كمّل",
  ok: "باهي",
  logout: "اخرج",

  // auth
  joinTitle: "اعمل كونت",
  joinHint: "بالنومرو متاعك برك",
  loginTitle: "مرحبا بيك",
  loginHint: "ادخل بنومرو التليفون",
  name: "اسمك",
  namePh: "مثلا: سامي",
  phone: "نومرو التليفون",
  password: "كلمة السر",
  passwordPh: "8 حروف ولا أرقام على الأقل",
  join: "اعمل الكونت",
  login: "ادخل",
  toLogin: "عندك كونت؟ ادخل",
  toJoin: "أوّل مرّة؟ اعمل كونت",
  errPhone: "النومرو لازمو 8 أرقام",
  errPassword: "كلمة السر لازمها 8 حروف ولا أرقام على الأقل",
  errName: "اكتب اسمك",
  errLogin: "النومرو ولا كلمة السر غالطين",
  errTaken: "النومرو هذا عندو كونت. ادخل بيه",
  errNetwork: "صار مشكل. عاود جرّب",
  errTooMany: "جرّبت برشا. استنّى ربع ساعة وعاود",
  forgot: "نسيت كلمة السر؟",
  forgotBody: "ابعثلنا ميساج على الواتساب من نفس النومرو، ونبعثولك كلمة سر جديدة.",
  forgotCta: "ابعثلنا على الواتساب",
  forgotMsg: "سلام، نسيت كلمة السر متاعي في Pointili",
  forgotNoContact: "قول للمحل اللي تتعامل معاه، وهو يكلّمنا.",
  newPassword: "كلمة سر جديدة",
  passwordChanged: "تبدّلت كلمة السر",
  change: "بدّل",
  openShop: "عندك محل؟",
  openShopHint: "حلّ كارط فيديليتي لمحلّك",
  myCardsHint: "الكارطات اللي لمّيتها في المحلات",

  // the scan
  checking: "لحظة…",
  newStamp: "تامبون جديد!",
  reserved: "حجزنالك التامبون",
  reservedBody: "اعمل كونت باش يولّي متاعك",
  reservedClock: "عندك 20 دقيقة",
  toGo: "مازالولك {n} باش تربح {gift}",
  toGoOne: "مازالك تامبون واحد باش تربح {gift}",
  won: "ربحت {gift}!",
  wonBody: "ورّي الكود متاع الكادو",
  seeCard: "شوف الكارط",
  done: "باهي",
  errUsed: "الكود هذا خذاه حدّ آخر",
  errUsedBody: "سكاني الكود اللي على الإيكران توّا",
  errExpired: "الكود وفى",
  errExpiredBody: "سكاني الكود اللي على الإيكران توّا",
  errSoon: "خذيت التامبون متاعك هوني",
  errSoonBody: "نتلاقاو المرّة الجاية! التامبون الجاي {when}",
  // when the next tampon comes
  soonAt: "على {time}",
  soonTomorrow: "غدوة",
  soonTomorrowAt: "غدوة على {time}",
  soonDay: "نهار {date}",
  soonDayAt: "نهار {date} على {time}",
  errDone: "التامبون هذا خذيتو",
  errOwn: "هذا المحل متاعك 🙂",
  errOwnBody: "الكود هذا للحرفاء",
  errInvalid: "الكود هذا موش صحيح",
  errPaused: "المحل هذا موقّف التامبونات توّا",
  scanAgain: "سكاني من جديد",

  // the wallet
  hello: "نهارك طيّب",
  myCards: "الكارطات متاعي",
  noCards: "ما عندكش كارطات مازال",
  noCardsBody: "سكاني الكود في المحل وخوذ أول تامبون",
  scan: "سكاني",
  giftWaiting: "عندك كادو يستنّى فيك",
  giftAt: "{gift} في {shop}",
  stamps: "{n} تامبونات",

  // a card
  ready: "الكادو متاعك حاضر!",
  readyBody: "ورّي الكود متاع الكادو في الكاسة",
  giftShow: "ورّي الكود متاع الكادو",
  giftCodeTitle: "الكادو متاعك: {gift}",
  giftCodeHint: "ورّي الكود هذا في الكاسة: يسكانيوه ويعطيوك الكادو",
  history: "شنوّة صار",
  hStamp: "تامبون",
  hGift: "خذيت {gift}",
  hGiftWaiting: "كادو يستنّى",
  nothingYet: "مازال ما صار شي",
  nextCard: "المحل بدّل الكارط: بعد الكادو هذا تولّي {gift} بعد {n}.",

  // the camera
  scanTitle: "سكاني الكود",
  scanHint: "حط الكود متاع المحل في وسط الإيكران",
  cameraOff: "الكاميرا ما خدمتش",
  cameraOffBody: "خلّي الكاميرا تخدم، ولا سكاني بكاميرا التليفون",
  photo: "صوّر الكود",

  // the account
  account: "الكونت",
  save: "سجّل",
  saved: "تسجّل",

  // the owner: open the shop
  shopNewTitle: "حلّ محلّك في Pointili",
  shopNewHint: "دقيقتين وتبدا تعطي تامبونات",
  ownerName: "اسمك",
  shopTitle: "المحل",
  shopName: "اسم المحل",
  shopNamePh: "مثلا: Café Yasmine",
  logo: "اللوغو",
  optional: "موش لازم",
  logoAdd: "زيد اللوغو",
  logoWait: "اللوغو مازال يطلع…",
  closeIt: "سكّر",

  // the owner's numbers, on their own screen
  statsTitle: "الأرقام",
  statsHint: "شنوّة صار في المحل متاعك",
  statCustomers: "حرفاء",
  statStamps: "تامبون في الكل",
  statGiven: "كادو تعطى",
  statWeek: "الجمعة هذي",
  statReturning: "حريف رجع أكثر من مرّة",
  statNewWeek: "حريف جديد الجمعة هذي",
  statTop: "أكثر الحرفاء",
  logoChange: "بدّل اللوغو",
  logoRemove: "نحّي اللوغو",
  errLogo: "ما نجمناش نقراو التصويرة، جرّب وحدة أخرى",
  errLogoBig: "التصويرة كبيرة برشا",
  logoTipTitle: "اللوغو متاعك هوني",
  logoTipBody: "تنجم تبدّلو وقتلّي تحب من «المحل».",
  logoTipTitleNone: "حطّ اللوغو متاعك",
  logoTipBodyNone: "موش لازم، أما يبان على كارط كل حريف. تنجم تحطّو وقتلّي تحب من «المحل».",
  logoTipNow: "نحطّو توّا",
  logoTipLater: "من بعد",
  logoTipOk: "باهي",
  shopKind: "شنوّة يبيع؟",
  kindsAll: "الكل",
  kindsTitle: "شنوّة يبيع محلّك؟",
  kindsSearch: "لوّج: عطورات، فريب، حمّام…",
  kindsNone: "ما لقيناش. اختار «آخر»",
  kinds: {
    cafe: "قهوة",
    juice: "عصير وجلاطي",
    bakery: "مخبزة",
    pastry: "حلويات",
    viennoiserie: "فطاير وكرواسون",
    crepes: "كريب وغوفر",
    restaurant: "ريستو",
    fastfood: "فاست فود",
    snack: "كسكروت وملاوي",
    pizza: "بيتزا",
    grill: "مشوي",
    grocery: "عطّار",
    market: "مغازة",
    butcher: "جزّار",
    fish: "حوت",
    veggies: "خضرة وغلّة",
    roastery: "محمصة",
    barber: "حلّاق",
    hair: "كوافير",
    beauty: "تجميل",
    nails: "ظوافر",
    perfume: "عطورات",
    parapharmacy: "بارافارماسي",
    hammam: "حمّام",
    optics: "نظّارات",
    gym: "رياضة",
    clothes: "لبسة",
    fripe: "فريب",
    shoes: "صبابط",
    bags: "ساكوات",
    jewelry: "بيجوتري",
    phones: "تليفونات",
    electronics: "إلكترونيك",
    books: "مكتبة",
    toys: "لعب صغار",
    gifts: "كادوات",
    flowers: "ورد",
    pets: "حيوانات",
    hardware: "دروقري",
    carwash: "لافاج",
    mechanic: "ميكانيك",
    laundry: "بريسينغ",
    tailor: "خيّاط",
    print: "طباعة",
    photo: "تصوير",
    courses: "دروس",
    games: "ألعاب",
    pitch: "ملاعب فوت",
    events: "حفلات",
    other: "آخر",
  } as Record<string, string>,
  cardTitle: "الكارط",
  cardGoal: "قدّاش من تامبون؟",
  cardGift: "شنوّة الكادو؟",
  cardGiftPh: "مثلا: قهوة بلاش",
  cardColor: "اللون",
  cardDone: "حلّ الكود",
  // the card, one question at a time
  wizOpened: "{shop} تحلّ في Pointili",
  wizTitle: "توّا نعملو مع بعضنا أوّل كارط فيديليتي متاعك",
  wizBody: "أربعة أسئلة برك، وفي دقيقة تكون حاضرة",
  wizStart: "يلّا نبداو",
  wizStep: "{n} من 4",
  wizEdit: "بدّل الكارط",
  wizGoalQ: "قدّاش من تامبون باش يربح الحريف كادو؟",
  wizGoalEx: "مثلا: 8 تامبونات وياخو قهوة بلاش",
  wizGoalOther: "ولا اكتب العدد",
  wizGoalRange: "من 3 لـ 30",
  wizGiftQ: "شنوّة يربح الحريف كي يكمّل الكارط؟",
  wizGiftEx: "مثلا: {a}، ولا {b}",
  wizGiftPh: "ولا اكتب الكادو متاعك",
  wizWaitQ: "كل قدّاش ينجم الحريف ياخو تامبون؟",
  wizWaitOther: "ولا اكتب عدد السوايع",
  wizWaitRange: "من 1 لـ 72",
  waitHour: "كل ساعة",
  waitDay: "مرّة في النهار",
  waitNone: "بلا حدّ",
  waitHourSays: "تامبون واحد في الساعة على الأكثر",
  waitDaySays: "تامبون واحد في النهار، والجاي غدوة",
  waitNoneSays: "كل مرّة يسكاني ياخو تامبون، بلا ما يستنّى",
  waitHoursSays: "تامبون واحد كل {n} على الأكثر",
  wizColorQ: "شنوّة لون الكارط؟",
  wizColorEx: "اختار لون يشبه لمحلّك",
  wizReady: "الكارط متاعك حاضرة!",
  wizReadyBody: "الحريف يسكاني الكود متاعك، وكل مرّة ياخو تامبون",
  wizReview: "هكّا تولّي الكارط",
  cardNoteNone: "حتى حريف ما بدا الكارط: الجديدة تبدا للكل توّا.",
  cardNoteEase: "اللي بداو الكارط ({who}) ياخذو الجديدة توّا.",
  cardNoteKeep: "اللي بداو الكارط ({who}) يكمّلوها كيما هي، والجديدة تبدالهم بعد الكادو.",
  ideas: {
    cafe: ["قهوة بلاش", "كابوسان بلاش", "كرواسون بلاش"],
    juice: ["عصير بلاش", "جلاطي بلاش", "ميلك شيك بلاش"],
    bakery: ["خبزة بلاش", "كرواسون بلاش", "قطعة قاتو بلاش"],
    pastry: ["قطعة قاتو بلاش", "كيلو حلويات بريميز", "ميلفاي بلاش"],
    viennoiserie: ["كرواسون بلاش", "فطيرة بلاش", "قهوة وكرواسون"],
    crepes: ["كريب بلاش", "غوفر بلاش", "مشروب بلاش"],
    snack: ["كسكروت بلاش", "ملاوي بلاش", "مشروب بلاش"],
    restaurant: ["ديسار بلاش", "مشروب بلاش", "صحن بلاش"],
    fastfood: ["سندويتش بلاش", "فريت ومشروب بلاش", "مشروب بلاش"],
    pizza: ["بيتزا صغيرة بلاش", "مشروب بلاش", "ديسار بلاش"],
    grill: ["صحن مشوي بلاش", "مشروب بلاش", "سلطة بلاش"],
    market: ["ريميز 5 د", "ريميز 10 د", "كادو سوربريز"],
    butcher: ["كيلو مرقاز بلاش", "ريميز 5 د", "ريميز 10%"],
    fish: ["كيلو سردينة بلاش", "تنظيف الحوت بلاش", "ريميز 5 د"],
    veggies: ["كيلو غلّة بلاش", "ريميز 3 د", "كادو سوربريز"],
    roastery: ["ربع كاكاوية بلاش", "ربع قلوب بلاش", "ريميز 10%"],
    barber: ["حجامة بلاش", "تعديل اللحية بلاش", "ريميز 10 د"],
    hair: ["بروشينغ بلاش", "سوان شعر بلاش", "ريميز 20%"],
    beauty: ["سوان وجه بلاش", "ريميز 20%", "كادو سوربريز"],
    nails: ["مانيكير بلاش", "فارني بلاش", "ريميز 20%"],
    perfume: ["عطر صغير بلاش", "ريميز 20%", "تغليف كادو بلاش"],
    parapharmacy: ["ريميز 10%", "كريمة بلاش", "كادو سوربريز"],
    hammam: ["دخلة حمّام بلاش", "تكييسة بلاش", "ريميز 20%"],
    optics: ["ريميز 20%", "تعديل النظّارات بلاش", "كادو سوربريز"],
    clothes: ["ريميز 10%", "ريميز 20 د", "كادو سوربريز"],
    fripe: ["قطعة بلاش", "ريميز 10%", "كادو سوربريز"],
    shoes: ["ريميز 10%", "ريميز 20 د", "كادو سوربريز"],
    bags: ["ريميز 10%", "أكسسوار بلاش", "كادو سوربريز"],
    jewelry: ["أكسسوار بلاش", "ريميز 20%", "تغليف كادو بلاش"],
    phones: ["كوك بلاش", "شارجور بلاش", "ريميز 10%"],
    electronics: ["كاسك بلاش", "شارجور بلاش", "ريميز 10%"],
    books: ["كرّاس بلاش", "ستيلو بلاش", "ريميز 10%"],
    toys: ["لعبة صغيرة بلاش", "ريميز 10%", "تغليف كادو بلاش"],
    flowers: ["وردة بلاش", "ريميز 10%", "تغليف بلاش"],
    pets: ["ماكلة بلاش", "ريميز 10%", "كادو سوربريز"],
    hardware: ["ريميز 10%", "ريميز 5 د", "كادو سوربريز"],
    grocery: ["ريميز 5 د", "كادو سوربريز", "قهوة بلاش"],
    gym: ["سيانس بلاش", "شهر بريميز", "مشروب بروتين بلاش"],
    games: ["بارتية بلاش", "ساعة بلاش", "كادو سوربريز"],
    events: ["ريميز 10%", "كادو سوربريز", "صورة بلاش"],
    carwash: ["لافاج بلاش", "تنظيف داخل بلاش", "ريميز 50%"],
    mechanic: ["فيدونج بلاش", "دياغنوستيك بلاش", "ريميز 20%"],
    laundry: ["قطعة بلاش", "ريميز 20%", "كادو سوربريز"],
    tailor: ["تقصير بلاش", "تصليح بلاش", "ريميز 20%"],
    print: ["10 صفحات بلاش", "تجليد بلاش", "ريميز 20%"],
    photo: ["صورة بلاش", "تصاور هوية بلاش", "ريميز 20%"],
    courses: ["حصّة بلاش", "ريميز 20%", "شهر بريميز"],
    pitch: ["ماتش بلاش", "ساعة بلاش", "مشروب بلاش"],
    gifts: ["ريميز 10%", "تغليف بلاش", "كادو سوربريز"],
    other: ["كادو بلاش", "ريميز 10 د", "كادو سوربريز"],
  } as Record<string, string[]>,
  preview: "هكّا يشوفها الحريف",
  // the card about to be saved, said plainly before it is
  cardPopNewTitle: "هكّا تخدم الكارط متاعك",
  cardPopNew1: "الحريف يسكاني الكود متاعك وياخو تامبون",
  cardPopNew2: "كي يكمّل {n} تامبونات يربح {gift}",
  cardPopNew2Sub: "يورّيك الكود متاعو وإنت تعطيه الكادو",
  cardPopNew3: "تنجم تبدّل الكارط وقتلّي تحب",
  cardPopNew3Sub: "واللي بداو ما يضيعولهم حتى تامبون",
  cardPopNewGo: "باهي، حلّ الكود",
  cardPopEditTitle: "شنوّة يتبدّل؟",
  cardPopGoal: "التامبونات",
  cardPopGift: "الكادو",
  cardPopWait: "كل قدّاش",
  cardPopColor: "اللون",
  cardPopWaitAll: "{wait}، للحرفاء الكل من توّا",
  cardPopNewOnes: "الحرفاء الجدد، واللي مازال ما بداوش، ياخذو الكارط الجديدة توّا",
  cardPopEased: "اللي الجديدة أسهل عليهم ({who}) ياخذوها توّا",
  cardPopWaiting: "{waiting}: كل حريف ياخو الكادو اللي ربحو",
  cardPopWay: "{who} بداو الكارط القديمة:",
  cardPopKeep: "يكمّلو كيما بداو",
  cardPopKeepSub: "ياخذو الكادو القديم، وبعدو تبدالهم الجديدة",
  cardPopMove: "يعدّيو للجديدة توّا",
  cardPopMoveSub: "التامبونات اللي عندهم يبقاولهم.",
  cardPopWinNow: "و{who} يربحو الكادو توّا.",
  cardPopSave: "سجّل",
  cardPopBack: "نرجع",

  // the counter
  counterTitle: "سكاني وخوذ تامبون",
  counterHint: "الكود يتبدّل وحدو، ويخدم مرّة برك",
  someone: "حريف",
  giftFor: "{who} ربح {gift}",
  giveNow: "يورّيك الكود متاع الكادو في تليفونو، وإنت سكانيه",
  given: "عطيتو ✓",
  noCardYet: "اعمل الكارط قبل",
  // help for an owner, set by the founder: a number to call, two videos
  helpCta: "عندك سؤال؟",
  helpTitle: "عندك سؤال؟",
  helpBody: "كلّمنا ونجاوبوك على أي سؤال، ولا شوف الفيديوات",
  helpCall: "كلّمنا",
  helpWhatsapp: "واتساب",
  helpWhatsappMsg: "سلام، عندي سؤال على Pointili",
  // the founder's settings and traffic
  aSettings: "الريڤلاج",
  aSettingsHint: "النومرو اللي يكلّمو عليه الموالي، والفيديوات",
  aSupportPhone: "نومرو المساعدة",
  aVideo1: "الفيديو الأوّل (كيفاش تخدم)",
  aVideo2: "الفيديو الثاني",
  aVideoLabel: "الكلام على البوتون",
  aVideoUrl: "لينك يوتيوب",
  aVideoBad: "اللينك هذا موش متاع يوتيوب",
  aSaved: "تسجّل",
  aTraffic: "الترافيك",
  // paying for the year: 120 a year; within 48 hours of opening, 3 more months
  payTitle: "الأبونمان",
  payPrice: "120",
  payCurrency: "د",
  payPer: "في العام",
  payPlan: "Pointili · عام كامل",
  payOfferBadge: "عرض خاص · 48 ساعة برك",
  payOfferTitle: "عام كامل + 3 شهور بلاش",
  payOfferBody: "خلّص الأبونمان قبل ما يوفى الوقت، وخوذ 15 شهر بسوم 12",
  payOfferLeft: "مازال",
  payOfferPlus: "+3 شهور بلاش",
  payHours: "ساعة",
  payMinutes: "دقيقة",
  paySeconds: "ثانية",
  payPerks: ["حرفاء بلا حدّ، وتامبونات بلا حدّ", "الكارط، الكود، والحرفاء متاعك في بلاصة وحدة", "نعاونوك في كل شي، بالتليفون ولا واتساب"],
  payNow: "نخلّص توّا",
  payLater: "من بعد",
  payBanner: "3 شهور بلاش كان تخلّص توّا",
  payBannerPlain: "الأبونمان: 120 د في العام",
  payBannerCta: "خلّص",
  payPending: "الخلاص متاعك يتثبّت",
  payPaidUntil: "مخلّص حتى {date}",
  payChoose: "اختار كيفاش تخلّص",
  payWays: "كيفاش تنجم تخلّص",
  payHow: "كلّمنا ولا ابعثلنا على واتساب، ونكمّلو الخلاص مع بعضنا في دقيقة",
  payWhatsappMsg: "سلام، نحب نخلّص الأبونمان متاع «{shop}» ({months} شهر)",
  payCard: "كارط بنكية",
  payCardSub: "Visa · Mastercard، في صفحة مضمونة",
  payD17: "D17",
  payD17Sub: "من الأبليكاسيون متاع البوسطة",
  payVirement: "Virement",
  payVirementSub: "من البنك متاعك",
  payVersement: "Versement",
  payVersementSub: "في أي فرع متاع البنك",
  payMandat: "Mandat",
  payMandatSub: "من أي بوسطة",
  payCardHow: "تخلّص بالكارط متاعك في صفحة مضمونة، وبعدها نفعّلولك الأبونمان",
  payCardGo: "نخلّص بالكارط",
  payD17How: "ابعث {amount} د على D17 للنومرو هذا",
  payRibHow: "ابعث {amount} د للحساب هذا",
  payVersementHow: "حطّ {amount} د في أي فرع متاع البنك، في الحساب هذا",
  payMandatHow: "ابعث Mandat بـ{amount} د من أي بوسطة",
  payName: "باسم",
  payBank: "البنك",
  payRib: "RIB",
  payAddress: "العنوان",
  paySent: "بعثت الفلوس",
  payCopy: "كوبي",
  payCopied: "تكوبى ✓",
  payAsk: "كلّمنا على واتساب ونعطيوك التفاصيل",
  payThanks: "وصلنا! يعيشك",
  payThanksBody: "نثبّتو ونفعّلو الأبونمان في أقل من 24 ساعة. ابعثلنا تصويرة الوصل باش يمشي فيسع",
  payProof: "ابعث تصويرة الوصل",
  payProofMsg: "سلام، خلّصت الأبونمان متاع «{shop}» بـ{method}",
  payMonths: "{n} شهر",
  // the founder's payments
  aPayments: "الخلاص",
  aPaymentsHint: "الموالي اللي قالو خلّصو: ثبّت كي توصلك الفلوس، والأبونمان يتحسب وحدو",
  aPayConfirm: "وصلت ✓",
  aPayRefuse: "ما وصلتش",
  aPayPending: "في الانتظار",
  aPayPaid: "مخلّص",
  aPayRefused: "ما وصلتش",
  aPayEmpty: "مازال حتى حد ما قال خلّص",
  aPayIncome: "اللي دخل",
  aPayContact: "كلّمنا / واتساب",
  aPaySettings: "تفاصيل الخلاص",
  aPayCardUrl: "لينك الخلاص بالكارط (Dodo Payments)",
  aPayD17: "نومرو D17",
  aPayName: "الحساب باسم",
  aPayBank: "البنك",
  aPayRib: "RIB (20 رقم)",
  aPayMandat: "العنوان متاع الـMandat",
  aTester: "كونت التجربة",
  aTesterHint: "تدخل بيه وتشوف Pointili كيما أي واحد، ورجّعو جديد وقتلّي تحب",
  aTesterFresh: "امسحو",
  aTesterFreshHint: "النومرو يولّي فارغ: تحلّ كونت من الأوّل",
  aTesterNew: "كونت بلا محل",
  aTesterNewHint: "تدخل من «ادخل كمولى محل» وتحلّ المحل خطوة بخطوة",
  aTesterOwner: "مولى قديم",
  aTesterOwnerHint: "محل تحلّ من 3 أيام، الكارط حاضرة",
  aTesterNone: "ما فمّاش كونت",
  aTesterAccount: "كونت بلا محل",
  aTesterShop: "عندو محل",
  aTesterMissing: "زيد TESTER_PHONE و TESTER_PASSWORD في .env.local",
  aTesterDone: "تعمل ✓",
  // real accounts and test accounts, apart in the console; the scripts' own never show
  aReal: "الحقيقيين",
  aTests: "التجربة",
  aTestBadge: "تجربة",
  aTestsHint: "الكونتات متاعك ومتاع التجربة: ما يدخلوش في الأرقام",
  aMarkTest: "حطّو مع التجربة",
  aMarkReal: "رجّعو مع الحقيقيين",
  aTestMine: "محل متاعك إنت: ديما مع التجربة",
  aTestsShops: "محلات التجربة",
  aTestsPeople: "كونتات التجربة",
  aRobots: "كونتات التيست الأوتوماتيك",
  aRobotsHint: "يتعملو وقت التيست ويتمسحو وحدهم، وما يظهروش مع المحلات. كان قعد منهم شي، امسحو من هنا.",
  aRobotsNone: "ما قعد حتى كونت",
  aRobotsLeft: "{n} قاعدين",
  aRobotsSweep: "امسحهم الكل",
  aRobotsDone: "تمسحو ✓",
  // the shop gives the tampon itself: the customer's code, scanned or typed
  collect: "زيد تامبون",
  collectHint: "اختار كيفاش",
  collectScan: "سكاني الكود متاع الحريف",
  collectScanShort: "سكاني",
  collectType: "اكتب الكود متاعو",
  collectTypeShort: "اكتب الكود",
  collectOr: "ولا خلّي الحريف يسكاني الكود متاعك",
  collectInput: "الكود (6 أرقام) ولا النومرو متاعو",
  collectLooking: "نلوّجو…",
  collectUnknown: "ما لقيناش حريف بالكود هذا",
  collectUnknownHint: "ما عندوش كونت؟ خلّيه يسكاني الكود متاعك ويحلّ كونت في دقيقة",
  collectGive: "زيد تامبون لـ{name}",
  collectGiveAnon: "زيد التامبون",
  collectDone: "لـ{name}!",
  collectDoneAnon: "تامبون!",
  collectGift: "{name} ربح {gift}!",
  collectSoon: "خذا التامبون متاعو. يرجع {when}",
  collectOwn: "هذا الكود متاعك إنت",
  collectNext: "حريف آخر",
  collectScanHint: "حط الكود متاع الحريف في وسط الإيكران",
  collectNoShop: "الكود هذا يخدم كان للمحلات",
  collectFirst: "أوّل مرّة عندك",
  collectGiftWaits: "عندو كادو يستنّى",
  collectGiftOpen: "عطيه",
  popGiftHas: "{name} عندو كادو!",
  popGiftAsk: "تعطيهولو توّا؟",
  popGiftGive: "إيه، عطيه الكادو",
  popGiftLater: "موش توّا",
  collectHanded: "{name} خذا {gift}",
  myCode: "الكود متاعي",
  myCodeTitle: "الكود متاعك",
  myCodeHint: "ورّيه للمحل، ولا قولّو النومرو متاعك، ويزيدك التامبون",
  publicCodeTitle: "هذا كود كارط Pointili",
  publicCodeBody: "ورّيه للمحل باش يزيدك تامبون",
  tourNext: "كمّل",
  // news for the owners: once each, from the console
  newsBadge: "جديد في Pointili",
  newsOk: "فهمت",
  aNews: "الأخبار",
  aNewsHint: "حاجة جديدة لازم يعرفوها الموالي؟ تطلعلهم مرّة وحدة كي يحلّو الأبليكاسيون، وتشوف شكون شافها وشكون لا",
  aNewsRule: "تطلع مرّة وحدة لكل مولى، وحدة في النهار على الأكثر، وكان للمحلات اللي تحلّو قبل ما تنشرها",
  aNewsNew: "خبر جديد",
  aNewsEmpty: "مازال ما نشرت حتى خبر",
  aNewsTitle: "العنوان",
  aNewsTitlePh: "مثلا: توّا تنجم تحط اللوغو متاعك",
  aNewsBody: "الكلام",
  aNewsBodyPh: "جملة ولا زوز: شنوّة الجديد، وعلاش يهمّو",
  aNewsIcon: "التصويرة",
  aNewsCta: "يمشي لوين؟ (موش لازم)",
  aNewsCtaNone: "بلاش بوتون",
  aNewsCtaLabel: "الكلام على البوتون",
  aNewsCtaLabelPh: "مثلا: جرّبها توّا",
  aNewsCtaLink: "اللينك (https://…)",
  aNewsToShop: "المحل (الإسم واللوغو)",
  aNewsToCard: "الكارط",
  aNewsToCustomers: "الحرفاء",
  aNewsToCode: "الكود",
  aNewsToAccount: "الكونت",
  aNewsToLink: "لينك آخر",
  aNewsPreview: "هكّا يشوفوها",
  aNewsPublish: "انشرها للموالي",
  aNewsAudience: "الموالي",
  aNewsSeen: "شافوها",
  aNewsClicked: "نزلو على البوتون",
  aNewsNotYet: "مازالو ما شافوهاش",
  aNewsLive: "تخدم",
  aNewsStopped: "موقوفة",
  aNewsStop: "وقّفها",
  aNewsResume: "رجّعها",
  aNewsDelete: "افسخها",
  aNewsDeleteConfirm: "تفسخ الخبر هذا والأرقام متاعو؟",
  aNewsYou: "إنت",
  aNewsTapped: "نزل",
  aNewsTaps: "نزلو",
  aNewsErrTitle: "العنوان لازمو بين 2 و 80 حرف",
  aNewsErrBody: "الكلام طويل برشا (400 حرف على الأكثر)",
  aNewsErrLabel: "اكتب الكلام اللي على البوتون",
  aNewsErrLink: "اللينك لازم يبدا بـ https://",
  // the first time the code shows, right after the card
  coachBravo: "برافو {name}!",
  coachBravoAnon: "برافو!",
  coachReady: "الكارط متاعك حاضرة",
  coachShow: "توّا نورّيك الإيكران اللي يسكانيه الحريف",
  coachShowCta: "ورّيني",
  coachTipTitle: "هذا الكود اللي يسكانيه الحريف",
  coachTip: "عندك تليفون آخر؟ سكاني بيه الكود وشوف شنوّة يشوف الحريف",
  coachTipOk: "باهي، فهمت",
  coachHomeTap: "انزل على «ورّي الكود» وورّي الإيكران للحريف باش ياخو أوّل تامبون",
  coachHomeLater: "نشوفها بعد",
  reconnecting: "نعاود نتصل…",

  // the owner's home
  showCode: "ورّي الكود",
  showCodeHint: "الحريف يسكاني وياخو تامبون",
  todayTitle: "اليوم",
  numVisitors: "حريف اليوم",
  waitingTitle: "كادوات يستنّاو",
  lately: "آخر حركة",
  lateStamp: "{who} خذا تامبون",
  lateGift: "{who} ربح {gift}",
  lateGiven: "{who} خذا {gift}",
  options: "الخيارات",
  customersTitle: "الحرفاء",
  customersEmpty: "مازال حتى حريف",
  customersEmptyBody: "ورّي الكود للحرفاء وكل واحد يسكاني يولّي هوني",
  firstSteps: ["حلّ الكود", "الحريف يسكانيه بتليفونو", "ياخو تامبون ويبان هوني"],
  seeAll: "شوف الحرفاء الكل",
  never: "مازال",
  pausedBanner: "المحل موقّف من Pointili. كلّمنا.",
  ago: "قبل {n}",

  // the owner's settings
  settings: "المحل",
  numCustomers: "حريف",
  numToday: "تامبون اليوم",
  numGifts: "كادو اليوم",
  editCard: "بدّل الكارط",
  editShop: "بدّل المحل",
  openCounter: "حلّ الكود",

  // the founder's console
  admin: "الأدمين",
  aShops: "المحلات",
  aPeople: "الناس",
  aPaused: "موقّف",
  aCustomers: "حرفاء",
  aStamps: "تامبون في الكل",
  aToday: "تامبون اليوم",
  aGiven: "كادو تعطى",
  aWeek: "التامبونات، آخر 7 أيّام",
  aAllLive: "الكل يخدمو",
  aInAll: "في الكل",
  aNoneWaiting: "حتى كادو ما يستنّى",
  aCall: "كلّمو",
  aSearch: "لوّج بالاسم ولا النومرو",
  aNoCard: "ما عملش الكارط",
  aOwner: "المولى",
  aCreated: "تحلّ",
  aLast: "آخر حركة",
  aPause: "وقّف المحل",
  aResume: "رجّع المحل يخدم",
  aDelete: "امسح المحل",
  aDeleteConfirm: "متأكد؟ المحل والكارطات متاعو يتمسحو ما يرجعوش.",
  aTop: "أكثر الحرفاء",
  aRecent: "آخر الحركة",
  aCards: "كارطات",
  aShopOf: "محل",
  aAdminBadge: "أدمين",
  aNothing: "ما فمّا شي",
  aCardsOf: "الكارطات متاعو",
  aNoCardsOf: "ما عندو حتى كارط",
  aIsAdmin: "هذا أدمين: ما يتبدّلش من هوني",
  aReset: "اعطيه كلمة سر جديدة",
  aResetDone: "كلمة السر الجديدة",
  aResetHint: "ما تبانش مرّة أخرى. ابعثهالو توّا، ويبدّلها من الكونت متاعو.",
  aResetSend: "ابعثها على الواتساب",
  aResetMsg: "سلام {name}، كلمة السر الجديدة متاعك في Pointili: {password}",
  aDeletePerson: "امسح الكونت",
  aDeletePersonConfirm: "متأكد؟ الكونت والكارطات متاعو يتمسحو ما يرجعوش، وكان عندو محل يتمسح زادة.",
};

/** "مازالولك {n}" + { n: 3 } → "مازالولك 3" */
export function fill(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => (k in vars ? String(vars[k]) : `{${k}}`));
}

/** The 3D picture of a kind of shop. */
export function kindIcon(kind: string | null | undefined): string {
  return (
    {
      cafe: "coffee",
      juice: "juice",
      bakery: "bread",
      pastry: "cake",
      viennoiserie: "croissant",
      crepes: "waffle",
      restaurant: "plate",
      fastfood: "burger",
      snack: "flatbread",
      pizza: "pizza",
      grill: "poultry",
      grocery: "shop",
      market: "cart",
      butcher: "meat",
      fish: "fish",
      veggies: "carrot",
      roastery: "peanuts",
      barber: "barber",
      hair: "scissors",
      beauty: "lipstick",
      nails: "nailpolish",
      perfume: "lotion",
      parapharmacy: "pill",
      hammam: "soap",
      optics: "glasses",
      gym: "biceps",
      clothes: "dress",
      fripe: "tshirt",
      shoes: "shoe",
      bags: "handbag",
      jewelry: "ring",
      phones: "phone",
      electronics: "headphone",
      books: "books",
      toys: "teddy",
      gifts: "gift",
      flowers: "bouquet",
      pets: "paw",
      hardware: "toolbox",
      carwash: "car",
      mechanic: "wrench",
      laundry: "basket",
      tailor: "thread",
      print: "printer",
      photo: "camera",
      courses: "gradcap",
      games: "videogame",
      pitch: "soccer",
      events: "party",
      // the first app's kinds, should one ever come back
      salon: "scissors",
      shop: "shop",
    } as Record<string, string>
  )[kind ?? ""] ?? "pin";
}

/** Every kind of shop, in the order the owner sees them. */
export const KINDS = Object.keys(t.kinds);

/** The kinds in five groups, for the full list. */
export const KIND_GROUPS: { id: string; label: string; kinds: string[] }[] = [
  { id: "food", label: "ماكلة وشراب", kinds: ["cafe", "juice", "bakery", "pastry", "viennoiserie", "crepes", "restaurant", "fastfood", "snack", "pizza", "grill"] },
  { id: "house", label: "قضية الدار", kinds: ["grocery", "market", "butcher", "fish", "veggies", "roastery"] },
  { id: "beauty", label: "جمال وصحّة", kinds: ["barber", "hair", "beauty", "nails", "perfume", "parapharmacy", "hammam", "optics", "gym"] },
  { id: "things", label: "حوايج", kinds: ["clothes", "fripe", "shoes", "bags", "jewelry", "phones", "electronics", "books", "toys", "gifts", "flowers", "pets", "hardware"] },
  { id: "services", label: "خدمات وتفرهيد", kinds: ["carwash", "mechanic", "laundry", "tailor", "print", "photo", "courses", "games", "pitch", "events", "other"] },
];

/** The words an owner may type for a kind, besides its name: French, and other ways to say it. */
const KIND_WORDS: Record<string, string> = {
  cafe: "cafe coffee salon de the كافي شاي تاي شيشة قهاوي",
  juice: "jus glace ice cream milkshake عصاير ڤلاس",
  bakery: "boulangerie pain خبز كوشة",
  pastry: "patisserie gateau قاتو باتيسري",
  viennoiserie: "croissant viennoiserie فطايري",
  crepes: "crepe gaufre waffle",
  restaurant: "restaurant resto مطعم",
  fastfood: "fast food burger tacos makloub مقلوب بورغر تاكوس",
  snack: "sandwich casse croute chapati malfouf ملفوف شباتي لبلابي",
  pizza: "pizza pizzeria",
  grill: "grill rotisserie chawarma شوارمة روتيسري دجاج",
  grocery: "epicerie حانوت عطرية",
  market: "supermarche supermarket magasin general سوبرات",
  butcher: "boucherie boucher لحم",
  fish: "poissonnerie poisson حوّات",
  veggies: "fruits legumes خضّار غلال",
  roastery: "fruits secs noix cacahuete قلوب كاكاوية",
  barber: "barbier coiffeur homme حجامة",
  hair: "coiffure coiffeuse salon",
  beauty: "esthetique institut beaute cosmetique مكياج",
  nails: "ongles manucure",
  perfume: "parfum parfumerie عطر",
  parapharmacy: "parapharmacie pharmacie صيدلية",
  hammam: "hammam spa massage مساج",
  optics: "opticien lunettes",
  gym: "salle de sport fitness musculation",
  clothes: "vetements pret a porter boutique حوايج",
  fripe: "friperie",
  shoes: "chaussures sabbat",
  bags: "sacs maroquinerie accessoires",
  jewelry: "bijouterie bijoux مصوغ ذهب",
  phones: "telephone gsm portable",
  electronics: "electronique informatique",
  books: "librairie papeterie كتب",
  toys: "jouets enfants",
  gifts: "cadeaux",
  flowers: "fleuriste fleurs",
  pets: "animalerie animaux",
  hardware: "droguerie quincaillerie",
  carwash: "lavage voiture",
  mechanic: "garage mecanique",
  laundry: "pressing blanchisserie",
  tailor: "couture couturier",
  print: "imprimerie impression photocopie",
  photo: "photographe studio",
  courses: "cours formation ecole",
  games: "jeux playstation billard bowling",
  pitch: "foot football terrain تيران",
  events: "fetes mariage evenement",
  other: "autre",
};

/** Letters that are written several ways become one: أ إ آ → ا, ة → ه, ى → ي, no accents. */
export function plain(text: string): string {
  return text
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f\u064b-\u065f\u0670]/g, "")
    .replace(/[أإآ]/g, "ا")
    .replace(/ة/g, "ه")
    .replace(/ى/g, "ي")
    .replace(/\s+/g, " ")
    .trim();
}

/** Does this kind answer what the owner typed? Every word has to be found. */
export function kindMatches(kind: string, query: string): boolean {
  const hay = plain(`${t.kinds[kind] ?? ""} ${KIND_WORDS[kind] ?? ""} ${kind}`);
  return plain(query)
    .split(" ")
    .filter(Boolean)
    .every((w) => hay.includes(w));
}

/** Counting the Tunisian way: حريف واحد, زوز حرفاء, 5 حرفاء, 12 حريف. */
export function counted(n: number, one: string, two: string, few: string, many: string): string {
  if (n === 1) return one;
  if (n === 2) return two;
  const r = n % 100;
  return r >= 3 && r <= 10 ? `${n} ${few}` : `${n} ${many}`;
}
export const stampsN = (n: number) => counted(n, "تامبون واحد", "زوز تامبونات", "تامبونات", "تامبون");
export const customersN = (n: number) => counted(n, "حريف واحد", "زوز حرفاء", "حرفاء", "حريف");
/** The same gift, written twice: «قهوة بلاش» = «  قهوة  بلاش » (as the database's same_gift sees it). */
const squash = (x: string | null | undefined) => (x ?? "").trim().replace(/\s+/g, " ").toLowerCase();
export const sameGift = (a: string | null | undefined, b: string | null | undefined) => squash(a) === squash(b);
export const giftsN = (n: number) => counted(n, "كادو واحد", "زوز كادوات", "كادوات", "كادو");
/** ساعة, زوز سوايع, 3 سوايع, 12 ساعة */
export const hoursN = (n: number) => counted(n, "ساعة", "زوز سوايع", "سوايع", "ساعة");
export const accountsN = (n: number) => counted(n, "كونت واحد", "زوز كونتات", "كونتات", "كونت");
export const liveN = (n: number) => counted(n, "واحد يخدم", "زوز يخدمو", "يخدمو", "يخدمو");
export const pausedN = (n: number) => counted(n, "واحد موقّف", "زوز موقّفين", "موقّفين", "موقّفين");
/** كادو واحد يستنّى, زوز كادوات يستنّاو */
export const waitingN = (n: number) => (n === 0 ? t.aNoneWaiting : n === 1 ? `${giftsN(1)} يستنّى` : `${giftsN(n)} يستنّاو`);
